DEV: modify github actions
[CHANGED] this was a strange bug which I don't understand. A Pull Request
    affecting only documentation failed tests due to the following error:

    /opt/hostedtoolcache/Python/3.7.12/x64/bin/python: Error while finding module specification for 'pip' (AttributeError: module '__main__' has no attribute '__file__')

    I was able to replicate this in a local conda environment and it appears
    entirely due to some upstream change in python / pip. Changing the GHA
    from ``python -m pip install ...`` to ``pip install ...`` fixed this locally.

    This will need revisiting.